title: Pius Githugu # your name (or website title) here
logo: "Githugutech.github.io/images/profile.png.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Scientist at heart, with a passion for breathing data to life. I am leveraging data, building innovative, great data-driven products, solutions and better workflows for the consumer and enterprise space. I am utilizing my expertise and experience to solve complex business and societal challenges, helping companies answer burning questions, bringing convenience, powering data-driven processes, enhancing speedy growth, leads and transformation.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/githugu-pius-009b13180/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
